with T1 as (
        select 
            src.descripcion_catalogo,
            src.entidad_origen,
            src.clave_homologada
        from (
            SELECT 'FISICO' DESCRIPCION_CATALOGO,'CANALES_DE_VENTA' ENTIDAD_ORIGEN,'0' CLAVE_HOMOLOGADA UNION ALL
            SELECT 'VIRTUAL','CANALES_DE_VENTA','30' UNION ALL
            SELECT 'POS','SUBCANALES_DE_VENTA','11' UNION ALL
            SELECT 'APP','SUBCANALES_DE_VENTA','12' UNION ALL
            SELECT 'WEB','SUBCANALES_DE_VENTA','31' UNION ALL
            SELECT 'MOVIL','SUBCANALES_DE_VENTA','32' UNION ALL
            SELECT 'SHAPP','SUBCANALES_DE_VENTA','33' UNION ALL
            SELECT 'CAT','SUBCANALES_DE_VENTA','34' UNION ALL
            SELECT 'KIOSKO','SUBCANALES_DE_VENTA','35' UNION ALL
            SELECT 'Z1 METRO SUR','ZONAS_DE_LOCACION','1' UNION ALL
            SELECT 'Z2 METRO NTE','ZONAS_DE_LOCACION','2' UNION ALL
            SELECT 'Z3 CENTRO','ZONAS_DE_LOCACION','3' UNION ALL
            SELECT 'Z4 OCCIDENTE','ZONAS_DE_LOCACION','4' UNION ALL
            SELECT 'Z5 GOLFO','ZONAS_DE_LOCACION','5' UNION ALL
            SELECT 'Z6 NORESTE','ZONAS_DE_LOCACION','6' UNION ALL
            SELECT 'Z7 BAJIO','ZONAS_DE_LOCACION','7' UNION ALL
            SELECT 'Z8 NOROESTE','ZONAS_DE_LOCACION','8' UNION ALL
            SELECT 'Z9 SURESTE','ZONAS_DE_LOCACION','9' UNION ALL
            SELECT 'BODEGAS Y DEPOSITOS','ZONAS_DE_LOCACION','BODE' UNION ALL
            SELECT 'BOUTIQUES','ZONAS_DE_LOCACION','BOUT' UNION ALL
            SELECT 'RESTAURANTE','ZONAS_DE_LOCACION','REST' UNION ALL
            SELECT 'VAD','ZONAS_DE_LOCACION','VAD' UNION ALL
            SELECT 'W. SONOMA','ZONAS_DE_LOCACION','WSI' UNION ALL
            SELECT 'INCO','ESTADOS_DE_ORDEN_DE_VENTA','INCO' UNION ALL
            SELECT 'CONF','ESTADOS_DE_ORDEN_DE_VENTA','CONF' UNION ALL
            SELECT 'VALM','ESTADOS_DE_ORDEN_DE_VENTA','VALM' UNION ALL
            SELECT 'RALM','ESTADOS_DE_ORDEN_DE_VENTA','RALM' UNION ALL
            SELECT 'VBOD','ESTADOS_DE_ORDEN_DE_VENTA','VBOD' UNION ALL
            SELECT 'RBOD','ESTADOS_DE_ORDEN_DE_VENTA','RBOD' UNION ALL
            SELECT 'VCTE','ESTADOS_DE_ORDEN_DE_VENTA','VCTE' UNION ALL
            SELECT 'LIPR','ESTADOS_DE_ORDEN_DE_VENTA','LIPR' UNION ALL
            SELECT 'VMEN','ESTADOS_DE_ORDEN_DE_VENTA','VMEN' UNION ALL
            SELECT 'NMEN','ESTADOS_DE_ORDEN_DE_VENTA','NMEN' UNION ALL
            SELECT 'VFDX','ESTADOS_DE_ORDEN_DE_VENTA','VFDX' UNION ALL
            SELECT 'NFDX','ESTADOS_DE_ORDEN_DE_VENTA','NFDX' UNION ALL
            SELECT 'VUPS','ESTADOS_DE_ORDEN_DE_VENTA','VUPS' UNION ALL
            SELECT 'NENT','ESTADOS_DE_ORDEN_DE_VENTA','NENT' UNION ALL
            SELECT 'BACC','ESTADOS_DE_ORDEN_DE_VENTA','BACC' UNION ALL
            SELECT 'BACR','ESTADOS_DE_ORDEN_DE_VENTA','BACR' UNION ALL
            SELECT 'BAMM','ESTADOS_DE_ORDEN_DE_VENTA','BAMM' UNION ALL
            SELECT 'BAME','ESTADOS_DE_ORDEN_DE_VENTA','BAME' UNION ALL
            SELECT 'BADR','ESTADOS_DE_ORDEN_DE_VENTA','BADR' UNION ALL
            SELECT 'RACR','ESTADOS_DE_ORDEN_DE_VENTA','RACR' UNION ALL
            SELECT 'RACC','ESTADOS_DE_ORDEN_DE_VENTA','RACC' UNION ALL
            SELECT 'RAMM','ESTADOS_DE_ORDEN_DE_VENTA','RAMM' UNION ALL
            SELECT 'RAME','ESTADOS_DE_ORDEN_DE_VENTA','RAME' UNION ALL
            SELECT 'RADR','ESTADOS_DE_ORDEN_DE_VENTA','RADR' UNION ALL
            SELECT 'EPAR','ESTADOS_DE_ORDEN_DE_VENTA','EPAR' UNION ALL
            SELECT 'ENVD','ESTADOS_DE_ORDEN_DE_VENTA','ENVD' UNION ALL
            SELECT 'TECLADO','DISPOSITIVOS_DE_ENTRADA','1' UNION ALL
            SELECT 'SCANNER','DISPOSITIVOS_DE_ENTRADA','3' UNION ALL
            SELECT 'MSR','DISPOSITIVOS_DE_ENTRADA','4' UNION ALL
            SELECT 'PINPAD','DISPOSITIVOS_DE_ENTRADA','5' UNION ALL
            SELECT 'EWALLET','DISPOSITIVOS_DE_ENTRADA','6' UNION ALL
            SELECT 'FALL BACK','DISPOSITIVOS_DE_ENTRADA','7' UNION ALL
            SELECT 'VPL','SISTEMAS_DE_ORIGEN','VPL' UNION ALL
            SELECT 'SOMS','SISTEMAS_DE_ORIGEN','SOMS' UNION ALL
            SELECT 'ATG','SISTEMAS_DE_ORIGEN','ATG' UNION ALL
            SELECT 'TICKET ELECTRONICO','SISTEMAS_DE_ORIGEN','TE' UNION ALL
            SELECT 'ORDEN DE VENTA','TIPO_DE_DOCUMENTO','OV' UNION ALL
            SELECT 'REMISION','TIPO_DE_DOCUMENTO','RM' UNION ALL
            SELECT 'SEMANAL','FRECUENCIA_VISITA','SEMANAL' UNION ALL
            SELECT 'DIARIO','FRECUENCIA_VISITA','DIARIO' UNION ALL
            SELECT 'QUINCENAL','FRECUENCIA_VISITA','QUINCENAL' UNION ALL
            SELECT 'MENSUAL','FRECUENCIA_VISITA','MENSUAL' UNION ALL
            SELECT 'DOMICILIO EQUIVOCADO','CAUSA_NO_ENTREGA','DOE' UNION ALL
            SELECT 'CLIENTE AUSENTE','CAUSA_NO_ENTREGA','CAU' UNION ALL
            SELECT 'ENTREGA FUTURA','CAUSA_NO_ENTREGA','EFU' UNION ALL
            SELECT 'MERCANCIA MALTRATADA','CAUSA_NO_ENTREGA','MML' UNION ALL
            SELECT 'MERCANCIA EQUIVOCADA','CAUSA_NO_ENTREGA','MEQ' UNION ALL
            SELECT 'LA MERCANCIA NO CABE','CAUSA_NO_ENTREGA','NCA' UNION ALL
            SELECT 'PROBLEMA CON EL TRANSPORTE','CAUSA_NO_ENTREGA','PTR' UNION ALL
            SELECT 'SINIESTRO','CAUSA_NO_ENTREGA','SNR' UNION ALL
            SELECT 'NO LA QUIERE','CAUSA_NO_ENTREGA','NLQ 1' UNION ALL
            SELECT 'CLIENTE RECOGE EN TIENDA','CAUSA_NO_ENTREGA','CRT' UNION ALL
            SELECT 'CLIENTE CANCELA EN TIENDA','CAUSA_NO_ENTREGA','CCT' UNION ALL
            SELECT 'DEVOLUCION','CAUSA_NO_ENTREGA','DEV' UNION ALL
            SELECT 'ENTREGA EN PISO','CAUSA_NO_ENTREGA','EPI' UNION ALL
            SELECT 'MERCANCIA POR CANCELAR','CAUSA_NO_ENTREGA','PCN' UNION ALL
            SELECT 'OV C/EVENTO DE LISTA EUROPEA(CONSENTIDO)','CAUSA_NO_ENTREGA','LEU' UNION ALL
            SELECT 'ENTREGADA','CAUSA_NO_ENTREGA','ENT' UNION ALL
            SELECT 'APARTADA','CAUSA_NO_ENTREGA','APA' UNION ALL
            SELECT 'A SU ARRIBO','CAUSA_NO_ENTREGA','ASA' UNION ALL
            SELECT 'CANCELADA','CAUSA_NO_ENTREGA','CAN' UNION ALL
            SELECT 'CLIENTE AVISA','CAUSA_NO_ENTREGA','CLA' UNION ALL
            SELECT 'DEPURACION','CAUSA_NO_ENTREGA','DEP' UNION ALL
            SELECT 'ENTREGA POR DHL','CAUSA_NO_ENTREGA','DHL' UNION ALL
            SELECT 'EQUIVOCADA','CAUSA_NO_ENTREGA','EEE' UNION ALL
            SELECT 'ENTREGADA','CAUSA_NO_ENTREGA','ETO' UNION ALL
            SELECT 'ENTREGA POR FEDEX','CAUSA_NO_ENTREGA','FDX' UNION ALL
            SELECT 'MERCANCIA EQUVOCADA','CAUSA_NO_ENTREGA','MEE' UNION ALL
            SELECT 'MERCANCIA MALTRATADA POR PROVEEDOR','CAUSA_NO_ENTREGA','MMP' UNION ALL
            SELECT 'DOMICILIO NO REGISTRADO','CAUSA_NO_ENTREGA','NRS' UNION ALL
            SELECT 'ENTREGA EXITOSA POR DHL','CAUSA_NO_ENTREGA','OK' UNION ALL
            SELECT 'MERCANCIA SOBRE PEDIDO','CAUSA_NO_ENTREGA','PED' UNION ALL
            SELECT 'MERCANCIA RECOGIDA','CAUSA_NO_ENTREGA','REC' UNION ALL
            SELECT 'RUTA ESPECIAL','CAUSA_NO_ENTREGA','REP' UNION ALL
            SELECT 'RUTA FUTURA','CAUSA_NO_ENTREGA','RFU' UNION ALL
            SELECT 'ENTREGA POR UPS','CAUSA_NO_ENTREGA','UPS' UNION ALL
            SELECT 'MERCANCIA EN CAMINO A CASA DEL CLIENTE','CAUSA_NO_ENTREGA','VCT' UNION ALL
            SELECT 'ZONA EQUIVOCADA','CAUSA_NO_ENTREGA','ZEQ' UNION ALL
            SELECT 'REAPROVISIONAMIENTO STERLING','CAUSA_NO_ENTREGA','REA' UNION ALL
            SELECT 'ENVIO POR RED','CAUSA_NO_ENTREGA','ERD' UNION ALL
            SELECT 'OTRO METODO DE ENVIO','CAUSA_NO_ENTREGA','OME' UNION ALL
            SELECT 'CCA','CAUSA_NO_ENTREGA','CCA' UNION ALL
            SELECT 'ENVIO A DOMICILIO','TIPO_ENTREGA','ENVIO A DOMICILIO' UNION ALL
            SELECT 'C&C','TIPO_ENTREGA','C&C' UNION ALL
            SELECT 'MESA DE REGALOS','TIPO_ENTREGA','MESA DE REGALOS' UNION ALL
            SELECT 'MARKETPLACE','TIPO_VENTA','VMP' UNION ALL
            SELECT 'VENTAS A DISTANCIA','TIPO_VENTA','VAD' UNION ALL
            SELECT 'ALMACENES','TIPO_VENTA','ALMACENES' UNION ALL
            SELECT 'SHIPPING','TIPO_DIRECCION','S' UNION ALL
            SELECT 'BILLING','TIPO_DIRECCION','B' UNION ALL
            SELECT 'MEXICO','PAIS','CCA' UNION ALL
            SELECT 'JALISCO','ESTADO','JAL' UNION ALL
            SELECT 'CIUDAD DE MEXICO','ESTADO','CDMX' UNION ALL
            SELECT 'REGION CENTRO','PROVINCIA','RC' UNION ALL
            SELECT 'CIUDAD DE MEXICO','PROVINCIA','CDMX' UNION ALL
            SELECT 'GUADALAJARA','MUNICIPIO','GUAD' UNION ALL
            SELECT 'COYOACAN','MUNICIPIO','COY' UNION ALL
            SELECT 'GUADALAJARA','COLONIA','GUAD' UNION ALL
            SELECT 'PRADOS DE COYOACAN','COLONIA','PRADCOY' UNION ALL
            SELECT 'EMPRESA SKU','EMPRESA_SKU','1' UNION ALL
            SELECT 'CREACION','TIPO_ACTUALIZACION','C' UNION ALL
            select 'ACTUALIZACION','TIPO_ACTUALIZACION','A' UNION ALL
            select 'MDM','SISTEMAS_DE_ORIGEN','MDM'
        ) as src
    left join shared.catalogos dst 
    	on src.clave_homologada = dst.clave_homologada 
    	and src.entidad_origen = dst.entidad_origen
    where dst.clave_homologada is null 
    	and dst.entidad_origen is null
)
insert into shared.catalogos (id_catalogo,descripcion_catalogo,clave_homologada,entidad_origen,esta_borrado) 
select 
	nextval('shared.seq_catalogos_pk'),
	descripcion_catalogo,
	clave_homologada,
	entidad_origen,
	'N'
from T1